# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: required
os:
  - linux
 # - osx

env:
  - V=HEAD URL_BASE=http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastSuccessfulBuild/artifact/output/ci/ URL="$URL_BASE`wget -qO- $URL_BASE | grep -oP 'bazel-.*?-installer.sh' | uniq`" FLAGS='--worker_verbose --strategy=Javac=worker --strategy=Closure=worker'
  - V=0.3.2rc3 URL=https://storage.googleapis.com/bazel/0.3.2/rc3/bazel-0.3.2rc3-installer-linux-x86_64.sh FLAGS=''
  - V=0.3.1 URL=https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel-0.3.1-installer-linux-x86_64.sh FLAGS=''

before_install:
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --sandbox_debug \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,1,1.0 \
      examples/helloworld/cpp/... \
      examples/helloworld/go/... \
      examples/helloworld/java/... \
      examples/helloworld/closure/... \
      $FLAGS

notifications:
  email: false
