dist: trusty
sudo: required
osx_image: xcode8
language: java

os:
  - linux
  - osx

env:
  - V=0.4.5
  - V=0.4.4
  - V=0.4.3
  - V=0.4.1
  - V=0.3.1

before_install:
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
  - CI_ARTIFACT="bazel--installer.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - if [[ "$V" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
  - if [[ "$V" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      --strategy=Javac=worker \
      --strategy=Closure=worker \
      --deleted_packages=tests/external_proto_library \
      //examples/helloworld/closure/... \
      //examples/helloworld/cpp/... \
      //examples/helloworld/go/... \
      //examples/helloworld/grpc_gateway/... \
      //examples/helloworld/java/... \
      //examples/wkt/... \
      $FLAGS \
    && \
    (cd tests/external_proto_library && bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      --strategy=Javac=worker \
      --strategy=Closure=worker \
      //:*)

notifications:
  email: false
